### PR TITLE
port to rt-thread rt_i2c_client

### PR DESCRIPTION
**Pull request by tyustli**
fix some warning and port to rt-thread rt_i2c_client
tomorrow i will fit this packages to at24cxx series

### CODE REVIEW

**Comment by tyustli** [comment]
@XiaojieFan
please review this pull request

**Comment by tyustli** [comment]
@XiaojieFan
can you see this pull request?

**Comment by tyustli** [comment]
@XiaojieFan
hello please review this pull request

**Comment by tyustli** [comment]
@XiaojieFan
hello please review this pull request

**Comment by XiaojieFan** [comment]
i am very sorroy response until now. I will review this package in the near future.

**Pull request closed without merging**
